import type { TechNode } from './types'

export const militaryTree: TechNode[] = [
  {
    id: 'bronze_swords',
    name: 'Bronze Swords',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 0,
    y: 0,
    parents: [],
  },
  {
    id: 'leather_armor',
    name: 'Leather Armor',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 0,
    y: 200,
    parents: [],
  },
  {
    id: 'iron_working',
    name: 'Iron Working',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 420,
    y: 0,
    parents: ['bronze_swords'],
  },
  {
    id: 'chain_mail',
    name: 'Chain Mail',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 420,
    y: 200,
    parents: ['leather_armor'],
  },
  {
    id: 'steel_swords',
    name: 'Steel Swords',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 840,
    y: 0,
    parents: ['iron_working'],
  },
  {
    id: 'plate_armor',
    name: 'Plate Armor',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 840,
    y: 200,
    parents: ['chain_mail'],
  },
  {
    id: 'siege_engines',
    name: 'Siege Engines',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 1260,
    y: 100,
    parents: ['steel_swords', 'plate_armor'],
  },
  {
    id: 'war_tactics',
    name: 'War Tactics',
    icon: '/placeholder.svg',
    level: 0,
    maxLevel: 10,
    x: 1260,
    y: 300,
    parents: ['plate_armor'],
  },
]
